### ISSUE TITLE
Can't pass Stylus options

### ISSUE THREAD

**Issue by DavidOliver** [fansenze/snowpack-plugin-stylus#1]
Thanks for the plugin. I'm new to snowpack and am trying to get set up with an existing project that uses Stylus.

I believe it's currently not possible to pass Stylus options.

My use for options is to tell Stylus to use rupture, a media queries plugin.

I've managed to get something working by [referring to this](https://www.snowpack.dev/reference/plugins) and modifying `plugin.js`:

- changing the `module.exports`-setting function to accept the `pluginOptions` argument
- moving the assigning of `render` into the `module.exports`-setting function
- adding `use` to the arguments of the call to `render`

```
module.exports = function (_snowpackConfig, pluginOptions) {
  const render = async (filepath) => {
    return new Promise((resolve, reject) => {
      fs.readFile(filepath, { encoding: 'utf-8' }, (err, data) => {
        if (err) {
          reject(err);
        } else {
          compiler.render(data, { filename: filepath, use: pluginOptions.use }, (err, result) => {
            if (err) {
              reject(err);
            } else {
              resolve(result);
            }
          });
        }
      });
    });
  }

  return {
    // ...
  };
}
```

snowpack.config.js:
```
var rupture = require('rupture');

/** @type {import("snowpack").SnowpackUserConfig } */
module.exports = {
  plugins: [
    ['snowpack-plugin-stylus', { use: [rupture()] }],
  ],
}
```

But this probably isn't robust and doesn't allow for other options in addition to `use`.

**Comment by fansenze** [comment]
@DavidOliver support `options` for stylus render in `1.0.1`

**Comment by DavidOliver** [comment]
Thanks very much for the update!

I'm using these options, and Rupture is successfully being used (and I can include CSS from `node_modules`):

```
  plugins: [
    [
      'snowpack-plugin-stylus',
      {
        use: [rupture()],
        paths: ['./node_modules'],
      }
    ],
  ],
```

However, one option I don't seem to be able to set here is `includeCSS`, which should result in Stylus embedding CSS `@import`'ed, or `@require`'d directly into the CSS result, instead of outputting a CSS `@import '...';`. I think this may be because the `includeCSS` option applies to the resolver and evaluator  objects, but not the renderer. ([A search for the option here](https://github.com/stylus/stylus/search?q=includecss).)

Do you know if it's possible for me to set `includeCSS` some other way, or would another update be required?
