### ISSUE TITLE
contributions

### ISSUE THREAD

**Issue by robertmaier** [fansenze/snowpack-plugin-stylus#4]
Hey @fansenze,

Thanks for creating this plugin :)
We are planning to use it in our application at work. I do have some features I want to contribute if that is ok for you?
As a first step, I made some refactorings and added some tests to the plugin in https://github.com/fansenze/snowpack-plugin-stylus/pull/6

If you want to keep the plugin as it is right now, feel free to reject it - we would then just use a fork of it moving on.

Best Regards,
Robert

**Comment by fansenze** [comment]
refactor in `release v1.0.4`
