### ISSUE TITLE
Changes in imported files don't trigger live reloads

### ISSUE THREAD

**Issue by robertmaier** [fansenze/snowpack-plugin-stylus#8]
Assuming the following setup:

main.styl:
```
@import './variables.styl'
.main {
  background-color: $mainColor;
}
```

variables.styl:
```
$mainColor = red;
```

view.js:
```
import './main.styl';
 // view code
```

Currently, only changes in files that are directly loaded by the browser are triggering a live reload.

**Comment by fansenze** [comment]
thx your pr，the feature published in `1.0.6`
